FROM node:18-alpine3.17


WORKDIR /app

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
COPY tsconfig.json /app/tsconfig.json
COPY tsconfig.build.json /app/tsconfig.build.json
COPY src /app/src

RUN yarn install --frozen-lockfile

EXPOSE 3000

HEALTHCHECK CMD curl -fs http://localhost:3000/health || exit 1
CMD ["yarn", "start:dev"]